esphome:
  name: snowtel-tx
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
    priority: 1000
    then:
      - logger.log: "Enabling VEXT"
      - output.turn_on: vext_ctl

external_components:
  - source:
      type: local
      path: my_components
  - source: github://mrtoy-me/esphome-vl53l1x@main
    components: [vl53l1x]
    refresh: 0s

esp32:
  board: esp32-s3-devkitc-1 #heltec_wifi_lora_32_V3 #esp32-s3-devkitc-1
  #variant: ESP32S3
  framework:
    type: esp-idf

psram:
  mode: quad
  speed: 80MHz

# Enable logging
logger:
  #hardware_uart: "UART0"

ota:
  - platform: esphome
    password: ""

wifi:
  id: wificomp
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  output_power: 8.5dB
  enable_on_boot: false

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Snowtel-Lora Fallback Hotspot"
    password: ""

preferences:
  flash_write_interval: 10min

captive_portal:
web_server:
  include_internal: true
#  local: true

deep_sleep:
  run_duration: 20s
  sleep_duration: 1min
  id: deep_sleep_1

i2c:
  - id: bus_b # Sensors
    scan: true
    sda: GPIO41
    scl: GPIO42
    frequency: 100kHz

spi:
  clk_pin: GPIO9
  mosi_pin: GPIO10
  miso_pin: GPIO11

sensor:
  - platform: mlx90614
    i2c_id: bus_b
    update_interval: 5s
    ambient:
      id: ambient_temp
      name: "Temp: Ambient"
    object:
      id: object_temp
      name: "Temp: Object"
      emissivity: 0.98 # ~Snow

  - platform: vl53l1x
    i2c_id: bus_b
    distance_mode: long
    update_interval: 10s
    distance:
      name: Raw Distance
      id: raw_distance
    range_status:
      name: Range Status
      id: range_status

  - platform: template
    name: Distance
    id: distance
    device_class: "distance"
    state_class: "measurement"
    unit_of_measurement: "mm"
    accuracy_decimals: 0
    update_interval: 1s
    lambda: |-
      if (id(range_status).state > 0) {
        return NAN;
      } else {
        return id(raw_distance).state;
      }
    filters:
      - median:
          window_size: 15
          send_every: 15
          send_first_at: 15

  - platform: adc
    id: battery_voltage_raw
    internal: true
    update_interval: never
    pin: GPIO1

  - platform: template
    id: battery_voltage
    name: "Battery Voltage"
    accuracy_decimals: 2
    device_class: "voltage"
    state_class: "measurement"
    unit_of_measurement: "V"
    update_interval: 30s
    filters:
      - multiply: 4.9 # voltage divider 390/100
    lambda: |-
      id(adc_ctl).turn_on();
      delay(100);
      float adc = id(battery_voltage_raw).sample();
      id(adc_ctl).turn_off();
      return adc;

binary_sensor:
  - platform: packet_transport
    provider: snowtel-rx
    id: ota_mode
    remote_id: remote_ota
    trigger_on_initial_state: true # To ensure OTA state is correct on boot
    on_state:
      - logger.log:
          format: "OTA Mode: %s"
          args: ['x ? "ON" : "OFF"']
      - lambda: |-
          if (x) {
            id(deep_sleep_1).prevent_deep_sleep();
            id(wificomp).enable();
            id(led).turn_on().set_brightness(0.5).perform();
          } else {
            id(deep_sleep_1).allow_deep_sleep();
            id(wificomp).disable();
            id(led).turn_off().perform();
          }

switch:
  - platform: gpio
    id: adc_ctl
    internal: true
    pin:
      number: GPIO37
      inverted: false

output:
  - id: led_output
    platform: ledc
    pin: GPIO35
  - id: vext_ctl
    platform: gpio
    pin:
      number: GPIO36
      inverted: false

light:
  - platform: monochromatic
    name: "LED"
    id: led
    output: led_output
    internal: true

sx126x:
  dio1_pin: GPIO14
  cs_pin: GPIO8
  busy_pin: GPIO13
  rst_pin: GPIO12
  pa_power: 14
  bandwidth: 125_0kHz
  crc_enable: true
  frequency: 915000000
  modulation: LORA
  hw_version: sx1262
  rf_switch: true
  sync_value: [0x14, 0x24]
  preamble_size: 8
  spreading_factor: 7
  coding_rate: CR_4_5
  tcxo_voltage: 1_8V
  tcxo_delay: 5ms

packet_transport:
  platform: sx126x
  sensors:
    - object_temp
    - ambient_temp
    - distance
    - battery_voltage
